### ISSUE TITLE
[Feature Request]: Review configuration in JSON, XML and YAML

### ISSUE THREAD

**Issue by dpanshug** [infinispan/infinispan-console#401]
### Feature description

Currently, when creating a cache configuration, users can only review the configuration in JSON format. To offer greater flexibility and meet diverse user preferences, we plan to add tabs that allow users to easily switch between viewing the configuration in JSON, YAML, and XML formats.

Steps to reproduce:
1. Start console and open localhost:9000
2. Click on create a cache.
3. Click on next till last review page.
4. On review page you can see the Cache config in JSON.

Existing view:
![image](https://github.com/infinispan/infinispan-console/assets/97534722/ce329b95-960f-42e3-8f8d-572a974d39b7)

JIRA: https://issues.redhat.com/browse/ISPN-14098
### Anything else?

You can see configuration in different formats in Download section of Review page. 
![image](https://github.com/infinispan/infinispan-console/assets/97534722/31d3a5e0-1124-4bf9-b35c-657acba4dbd6)

**Comment by himanshu608** [comment]
Hi @dpanshug ,
In our codebase, 
we have a helper function ConsoleServices.caches()
        .convertToAllFormat,
which converts the code into different formats.
but the problem is it takes body parameter in json format, 
so we can convert json to other formats, But can't pass other formats 'xml' & 'yaml' as input of this function.

We can use useFetchConfigurationYAML hooks for initial code.
But the problem is, when the use wants to update the code, It will reflected in other code formats only if the json code is update. 

So, Do you have any api that we can use here, for conversion.

**Comment by dpanshug** [comment]
@himanshu608 You can find documentation related to this at https://infinispan.org/docs/stable/titles/rest/rest.html#rest_v2_cache_config_convert

For more discussion, you can write your queries in our [chat room](https://infinispan.zulipchat.com/#narrow/stream/118645-infinispan/topic/hacktoberfest)

And pls assign this ticket to yourself.
