### ISSUE TITLE
Cluster Viewing Error: "WFLYCTL0202: No known child type named host"

### ISSUE THREAD

**Issue by ianarsenault** [infinispan/infinispan-console#5]
Version: Infinispan 9.4 

I'm running infinispan 9.4 in standalone mode with a 2 node cluster. Monitoring the logs upon service startup both nodes join cluster without issue. Also I can see from the view of http:/localhost:9990/console/index.html#/server-groups that the cluster has 2 hosts/nodes avaialble. When I click into the cluster I get a http 500 response failure-description: "WFLYCTL0202: No known child type named host"

![Image](https://i.imgur.com/hHAiqAg.png)
![Image](https://i.imgur.com/vl0Csjg.png)

It appears the address is empty on the request

![Image](https://i.imgur.com/ZDp5G09.png)

**Comment by karesti** [comment]
Hi, this is not the console of Infinispan 9.4, but 10.x.
The 9.4 console is not under development anymore

**Comment by ryanemerson** [comment]
@ianarsenault FYI the old repoistory for 9.4.x is located at https://github.com/infinispan/infinispan-management-console/tree/9.4.x.

Your issue should have been resolved in `9.4.18.Final` by [ISPN-11097](https://issues.redhat.com/browse/ISPN-11097). If you're not currently using that version, please try upgrading to see if it resolves your issue. As @karesti states, 9.4.x console is no longer in development, so if the issue is not resolved by ISPN-11097 then we cannot provide further support. I would highly recommend migrating to Infinispan 10.1.x where you can get lots of new features as well as the new console :slightly_smiling_face:.

**Comment by karesti** [comment]
@ryanemerson thanks for the further information!

**Comment by ianarsenault** [comment]
Thanks for the info @karesti and @ryanemerson
